id: P000558
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W29653
  title: ལས་བརྒྱ་པ།
  author: ''
  volumes:
    8e26573b98264021bc5c3e13b6983620:
      image_group_id: I1KG20827
      title: Volume 1 of las brgya tham pa
      volume_number: 1
      total_pages: 806
      base_file: v001.txt
